### ISSUE TITLE
Error while running make

### ISSUE THREAD

**Issue by bhanurapelly** [Ruunyox/bklk#1]
In main.cpp line 32, exit was not declared in this scope. I am attaching a screenshot for more information.
![2020-11-01_10-59](https://user-images.githubusercontent.com/37453827/97795864-909b3c80-1c31-11eb-812c-de255e0221b3.png)
Help is appreciated.

**Comment by Ruunyox** [comment]
Thanks for bringing this up! Looks like some includes might have changed/removed in newer versions of gcc, so this will can be fixed by adding `#inlcude <cstdlib>` in `main.cpp`. I will commit this and update you when it is done and works.

**Comment by Ruunyox** [comment]
Give `make` another try and see if it works after [the latest commit](https://github.com/Ruunyox/bklk/commit/26f3420aa5726e152a745278ddb98dc99c0a935e). I tested everything on my end (color cycling, m/s options, dynamic resizing) on my end and and still works. Let me know if there are any outstanding issues on your end!

**Comment by Ruunyox** [comment]
I'm going to close this issue for now - if there are any further problems, feel free to open a new issue!
